environment:
  GOBIN: c:\gobin

install:
  - rmdir c:\go /s /q
  - curl -O https://storage.googleapis.com/golang/go1.12.windows-amd64.msi
  - msiexec /i "go1.12.windows-amd64.msi" /q

build: false

test_script:
  - go install github.com/rakyll/statik
  - c:\gobin\statik.exe -src=.\public
  - go test ./...

deploy_script:
  - go install github.com/goreleaser/goreleaser
  - if %APPVEYOR_REPO_TAG% equ true c:\gobin\goreleaser.exe release
